name: linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        distro:
          - archlinux
          - opensuse

    runs-on: ubuntu-latest
    container:
      image: alexays/waybar:${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: meson -Dman-pages=enabled -Dexperimental=true build
      - name: build
        run: ninja -C build
      - name: test
        run: meson test -C build --no-rebuild --print-errorlogs --suite waybar
